# Add admin SSH keys for the provisioning user on the Admin VM
- name: Create .ssh directory
  file:
    path: /home/adm/.ssh/
    state: directory
    recurse: yes
- name: Add SSH keys for admins
  copy:
    src: "./files/.ssh/authorized_keys"
    dest: "/home/adm/.ssh/authorized_keys"

# Install needed tools
- name: Install packages required on the admin host
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - ansible

- name: Add an apt signing key for kubectl
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add an apt signing key for helm
  apt_key:
    url: https://helm.baltorepo.com/organization/signing.asc
    state: present

# Kubectl
- name: Add apt repo for kubectl
  apt_repository:
    repo: 'deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
- name: Add apt repo for helm
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present

- name: Install Kubernetes and helm binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - kubectl
    - helm
  notify:
  - kubectl version client
  - helm version

# Fail2ban && SendMail
- name: Install fail2ban
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - fail2ban
    - sendmail
  notify:
  - fail2ban status
  - sendmail status

- name: Configure fail2ban
  copy:
    src: "./files/fail2ban/fail2ban.local"
    dest: "/etc/fail2ban/fail2ban.conf"
- name: Create jail.conf local
  copy:
    src: "./files/fail2ban/jail.local"
    dest: "/etc/fail2ban/jail.conf"

# Download the latest RKE binary
- name: Download and install the latest RKE binary
  get_url:
    url: https://github.com/rancher/rke/releases/download/v1.1.4/rke_linux-amd64
    dest: /usr/local/bin/rke
    mode: 0755

- name: Add helm repo for Rancher
  become: yes
  become_user: adm
  command: 'helm repo add rancher-latest https://releases.rancher.com/server-charts/latest'
